<!-- 摄像头相关的 xacro 文件 -->
<robot name="Robot_gyro" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 摄像头属性 -->
    <xacro:property name="gyro_length" value="0.01" /> <!-- 摄像头长度(x) -->
    <xacro:property name="gyro_width" value="0.01" /> <!-- 摄像头宽度(y) -->
    <xacro:property name="gyro_height" value="0.005" /> <!-- 摄像头高度(z) -->
    <xacro:property name="gyro_x" value="-0.08" /> <!-- 摄像头安装的x坐标 -->
    <xacro:property name="gyro_y" value="0.0" /> <!-- 摄像头安装的y坐标 -->
    <xacro:property name="gyro_z" value="${base_link_length / 2 + gyro_height / 2}" /> <!-- 摄像头安装的z坐标:底盘高度 / 2 + 摄像头高度 / 2  -->

    <!-- 摄像头关节以及link -->
    <link name="gyro">
        <visual>
            <geometry>
                <box size="${gyro_length} ${gyro_width} ${gyro_height}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="black" />
        </visual>
    </link>

    <joint name="gyro2base_link" type="fixed">
        <parent link="base_link" />
        <child link="gyro" />
        <origin xyz="${gyro_x} ${gyro_y} ${gyro_z}" />
    </joint>
</robot>
